name: wed_plan_project
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localization: ^0.1.14
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: null
  intl: ^0.18.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  rxdart: ^0.27.7
  transparent_image: ^2.0.1
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  hive_generator: null
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo/logo1.jpg'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    
flutter_intl:
  enabled: true
